### ISSUE TITLE
半精度训练是否会影响收敛后性能？

### ISSUE THREAD

**Issue by splinter21** [xxh96/ADCSR#10]

**Comment by xxh96** [comment]
训练不用半精度，只是测试用的，用于减少显存占用，测试不会引起性能降低。我好像很早之前尝试过使用半精度训练，但没有成功。若你成功了，请告知，谢谢。

**Comment by splinter21** [comment]
我半精度训练没有成功，开头就十几位的loss，或者开头loss很大后面loss就爆了，对于很深的网络，很容易就失败了。

**Comment by splinter21** [comment]
不过FP16测试不会影响性能就好，如果是int8是不是还得fine-tune了。
