### ISSUE TITLE
有关readme里面的超参

### ISSUE THREAD

**Issue by splinter21** [xxh96/ADCSR#12]
1、act在option.py里已经有了，不是add是修改
2、对照模型代码，测试命令里面的--block_feat应该改为--block_feats，并在option.py里加上

**Comment by splinter21** [comment]
3、adc16_12里面251行r_mean.g_mean,b_mean也要同2一样加上(dsadcsr里面300行)

**Comment by splinter21** [comment]
测试总算跑起来了。。
所有有关n_resblocks是否写成n_resblock也需要校对下。。
另外，代码里A和B的scale是写死4个的，不是根据n_resblock动态变化，这样没法拓展
最后吐槽下，我的渣渣1080Ti加上半精度测试总算没有爆显存了。。这个模型真是大得可怕

**Comment by xxh96** [comment]
恭喜，这些参数的确需要，我的错，祝你好运

**Comment by xxh96** [comment]
测试命令行只要几个字母是单独的就不用完全写完

**Comment by xxh96** [comment]
11gGPU显存使用半精度可以完成B100+Urabn100+manga109的测试，但若要跑DIV8K测试需要12G显存
