### ISSUE TITLE
为什么head_conv不带wn？

### ISSUE THREAD

**Issue by splinter21** [xxh96/ADCSR#13]
https://github.com/xxh96/ADCSR/blob/079e1f6636ee5458ac5f458c7b4f99351d4e764a/adcsr.py#L215
https://github.com/xxh96/ADCSR/blob/079e1f6636ee5458ac5f458c7b4f99351d4e764a/dsadcsr.py#L300

**Comment by robinaman** [comment]
我也有同样问题，你找到答案了吗
