### ISSUE TITLE
预训练skip分支有没有对照实验？

### ISSUE THREAD

**Issue by splinter21** [xxh96/ADCSR#2]
实验1：预训练skip，冻结skip，训练主分支
实验2：两分支同时训练
实验3：预训练skip，两分支同时训练

**Comment by xxh96** [comment]
4.3 Pretraining SKIP 中的：
a. 直接训练整个网络；
b. 首先预训练SKIP,之后同时训练整个网络;
c. 首先预训练SKIP,之后单独训练BODY 。

**Comment by splinter21** [comment]
明白了

**Comment by splinter21** [comment]
就是说SKIP分支还是要提前训练好，能对结果有帮助。
不过其实就引出一个问题，你自己训练一个玩具skip，把现有的预训练模型当skip不是挺好么，比如edsr啊rcan之类的。
然后因为b和c差不多说明skip层不再训练不会有性能下降，那么可以拿那些现成的预训练模型跑一遍求好残差存成npy/pt文件代替原有的读取png图像存npy/pt

**Comment by splinter21** [comment]
就是说SKIP分支还是要提前训练好，能对结果有帮助。
不过其实就引出一个问题，你自己训练一个玩具skip，把现有的预训练模型当skip不是挺好么，比如edsr啊rcan之类的。
然后因为b和c差不多说明skip层不再训练不会有性能下降，那么可以拿那些现成的预训练模型跑一遍求好残差存成npy/pt文件代替原有的读取png图像存npy/pt

**Comment by splinter21** [comment]
就是说SKIP分支还是要提前训练好，能对结果有帮助。
不过其实就引出一个问题，比起你自己训练一个玩具skip，把现有的预训练模型当skip不是挺好么，比如edsr_baseline或者其他lightweight_sr之类的(不怎么影响测试速度)。
然后因为b和c差不多说明skip层不再训练不会有性能下降，那么可以拿那些现成的预训练模型跑一遍求好残差存成npy/pt文件代替原有的读取png图像存npy/pt（别存成图像uint8，会丢失精度），不影响训练速度。
@xxh96

**Comment by xxh96** [comment]
SKIP没有非线性层，没有激活函数，我想让BODY专注HR于SKIP之前的细节差，若选择EDSR等需要是训练HR与EDSR之间的差，会增加网络计算量和参数量，但效果怎么样我不知道，我也没有测试过。
