### ISSUE TITLE
结尾的这个上采样缺少对照实验

### ISSUE THREAD

**Issue by splinter21** [xxh96/ADCSR#3]
对比AWMS，先shuffle再在高分辨率尺度conv压通道+去掉adaptive这两点，再加上一个普通sub-pixel的baseline，都需要对比一下。

**Comment by xxh96** [comment]
4.2 节中table 1就是三种实验啊，conv压通道实现特征融合，这里相当于直接用训练卷积控制亚像素卷积的权重，是同时进行。

**Comment by splinter21** [comment]
抱歉，看漏了orz
不过感觉提升还是很微小的，在0.002这个级别，我印象中Urban100和Manga109这2个数据集PSNR是变化幅度会比较大的。不过有就行了，比没有好。
